version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    volumes:
      - $HOME/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=mssql1Ipw
      
  mailing:
    image: dockage/mailcatcher:0.8.2
    ports:
      - "1080:1080"
      - "1025:1025"
        
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "7217:7217"
      - "5151:5151"